# Generated by Django 4.2.17 on 2025-01-13 08:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Description of the project', null=True)),
                ('website_link', models.URLField(default='https://www.google.com')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
