# Generated by Django 3.1.5 on 2024-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('website_link', models.URLField()),
            ],
        ),
    ]
