# Generated by Django 3.1.5 on 2024-07-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240721_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./static/project_img'),
        ),
    ]
