# Generated by Django 3.1.5 on 2025-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240807_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='website_link',
            field=models.URLField(default='#'),
        ),
    ]
